### ISSUE TITLE
Park shipment not check the qoh of Assert

### ISSUE THREAD

**Issue by chunlinyao** [moqui/PopCommerce#15]
I can park a shipment with quantity greater than qoh of assert. The following steps.
1. Reload db
2. Create a sales order from FindOrder screen.
3. Add a item of DEMO_1_1 with quantity=500 and PlaceOrder, Approve Order
4. Click Create Shipment.
5. At ShipmentDetail screen, Set Scheduled -> Set Picket -> Pack
6. The Pack succeeded. Goto the asset detail screen, The qoh of DEMO_1_1A will be -400

It seems line 1013~1035 of ShipmentServices.xml forget checking qoh.

**Comment by jonesde** [comment]
This is intentional (and BTW this is an aspect of Mantle, not PopCommerce; all data model and logic/services for PopCommerce are in Mantle).

The general idea is that the physical inventory is more important than what the system thinks the inventory is. If you ship 100 of product X but only have 90 on hand, it means the system was off and it should be allowed.

Right now this will result in a negative QOH, but is really a found physical inventory event and most organizations will want an automatic physical inventory showing the additional inventory as found, bringing the QOH back up to zero.

**Comment by chunlinyao** [comment]
But the behavior is not consistent. When pass a assetId parameter in, It not allow negative QOH.
