### ISSUE TITLE
moqui without demo data gives error

### ISSUE THREAD

**Issue by hansbak** [moqui/PopCommerce#42]
When i install moqui with the following commands to NOT load the demo data:
1. git clone https://github.com/moqui/moqui-framework.git moqui
2. cd moqui
3. ./gradlew getComponent -Pcomponent=PopCommerce
4. java -jar moqui.war load types=seed,seed-initial,install
5 java -jar moqui.war

browser: localhost:8080
create new user admin
login with user admin i get the error:

Error updating Visit {visitId=100000}
×Close
Tried to update a value that does not exist [[moqui.server.Visit: {lastUpdatedStamp=2020-03-08 20:46:40.623, visitId=100000, thruDate=2020-03-08 20:46:40.654}]]. SQL used was UPDATE VISIT SET THRU_DATE=?, LAST_UPDATED_STAMP=? WHERE VISIT_ID=?, parameters were [thruDate:2020-03-08 20:46:40.654, lastUpdatedStamp:2020-03-08 20:46:40.623, visitId:100000]
×Close
Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=true]. Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).

Regards,
Hans

**Comment by jonesde** [comment]
I just tested this locally and the initial admin user plus login after worked fine.

The error about updating a Visit that doesn't exist is normal in dev environments, the browser you hit it will probably had a cookie already and it submitted that with the request but the visit ID in the cookie was not in the database because it was from a prior run.

The second error looks like a partial one, was that the only thing in the logs? I'm guessing there was more to it, and perhaps a stack trace. More info would be needed as that is just an exception from Shiro and most likely wraps another exception.

**Comment by hansbak** [comment]
Ok, deleting the cookies in the browser, solved both problems.
