### ISSUE TITLE
outgoing payment appear at originating party financial tab as an incoming payment

### ISSUE THREAD

**Issue by growerp** [moqui/PopCommerce#45]
How to create:
1. create an outgoing payment.
2. look at the originating party detail screen
3. click on financial info
4. see the outgoing payment as an Unapplied Incoming Payments listed.

**Comment by jonesde** [comment]
The reason they seem backward is you are looking at an Internal Organization. This is easy to see from the demo data and the data from the automated tests which are on the demo.moqui.org server:

https://demo.moqui.org/vapps/PopcAdmin/Party/FinancialInfo?partyId=ORG_ZIZI_RETAIL

This isn't just the Unapplied Incoming Payments section, it would apply to all because all of them use terms that are only correct if the Party you're looking at is a Customer or Supplier as Internal Organizations are always the other side of Invoices, Payments, and Orders.

The labels there are not actually directly accurate. Starting at the top with 'Receivables' that really means Invoices where the current Party is the To Party (an internal org being the From Party, hence the term 'receivable').

This screen isn't actually meant for use with internal organizations, for an internal org you can look at the accounting screens which have much more information and are designed for scale where this screen is most definitely not. I thought I had already added a condition so that it just shows a message if the current Party has the 'Internal' Role, mainly because I looked at it once on a live system for a busy internal org and it was so massive it was unusable (thousands of invoices, payments, and orders displayed), and I was kind of surprised it was able to render it at all.

Anyway, I hope that explains the labels and how they only make sense from one perspective. While we could change all the labels to things like 'Invoices To' instead of 'Receivables' IMO that makes it much more confusing for the primary intended use of the screen.

I'll add a conditional message and change it so it doesn't query or display any of the results for Internal Organizations (Party with the 'Internal' role).

**Comment by jonesde** [comment]
The change to not display for internal orgs and recommends using the Accounting screens and reports is in commit 556d4c2 in the SimpleScreens repo (where the FinancialInfo.xml screen lives).
